doctrine:
    dbal:
        default_connection: mysql
        connections:
            mysql:
                url: '%env(resolve:DATABASE_MYSQL_URL)%'
            local:
                url: '%env(resolve:DATABASE_LOCAL_URL)%'
    orm:
        auto_generate_proxy_classes: false
        default_entity_manager: mysql
        entity_managers:
            mysql:
                connection: mysql
                mappings:
                    default:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Domain/Mysql'
                        prefix: 'App\Domain\Mysql'
                        alias: App
            local:
                connection: local
                mappings:
                    default:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Domain/Local'
                        prefix: 'App\Domain\Local'
                        alias: App